### ISSUE TITLE
Debian dependencies

### ISSUE THREAD

**Issue by olaf7** [scm-manager/scm-manager#1223] opened 2020-06-29 12:23 UTC
SCM-server 2.1.1 package (Debian) introduced the need for 'at', but this package is not a dependency.

scm-server probably also requires package 'jsvc' as well, but again this is not a dependency.

**Comment by sdorra** [comment] 2020-06-29 12:33
The missing `at` dependency is a duplicate of #1216 and `jsvc` is a binary which is included in the debian package.

**Closed by sdorra** 2020-06-29 12:33 UTC
Labels: duplicate
