### ISSUE TITLE
scm-manager 2.10.0 Activity Plugin Java Language 500 Error

### ISSUE THREAD

**Issue by mperyer1** [scm-manager/scm-manager#1445] opened 2020-11-25 11:59 UTC
## Issue description

I'm currently setting up a new scm-manager 2.10 Server to use with mercurial, i added the activities plugin and whenever i try to access the "Activities" page I get the attached error.

Note: The repositories are being migrated from scm-manager 1.35 using the mercurial commandline. As written in: https://www.scm-manager.org/docs/2.9.x/en/import/

#### Describe how to reproduce the bug

Install the Plugin "Activity" from http://<IP Address>:8080/scm/admin/plugins/available/

#### Describe your SCM-Manager setup

Plugins in use:
- LDAP 2.0.1
- SSH 2.2.1
- Activity 2.0.0
- Statistic 2.0.0
- Cockpit 2.0.0
- Legacy 2.10.0
- Rest 2.0.0
- Mail 2.3.0
- Git 2.10.0
- Mercurial 2.10.0
- Subversion 2.10.0

There are no Proxy Settings and the Server is not sat behind a Reverse Proxy.

The scm-manager server is using the default web engine from the YUM Repository.

#### Which operating system, browser and versions do you use?

scm-manager is installed on a CentOS Linux release 7.9.2009 (Core) VM

I'm currently working on it from a Windows 10 PC with Google Chrome Version 86.0.4240.183.

#### Log of the bug

`2020-11-25 06:53:59.912 [qtp670576685-12] [          ] WARN  sonia.scm.security.DefaultAccessTokenCookieIssuer - issuet a non secure cookie, protect your scm-manager instance with tls https://goo.gl/lVm0ph
2020-11-25 06:54:00.000 [qtp670576685-12] [51SHLx5Sq2I] WARN  org.eclipse.jgit.lib.Repository - close() called when useCnt is already zero for Repository[/var/lib/scm/repositories/9FSGhuMwOi/data]
2020-11-25 06:54:00.098 [qtp670576685-12] [51SHLx5Sq2I] WARN  sonia.scm.api.FallbackExceptionMapper - mapping unexpected java.lang.IllegalStateException to status code 500
java.lang.IllegalStateException: Server pool is stopped
	at com.aragost.javahg.internals.ServerPool.take(ServerPool.java:148)
	at com.aragost.javahg.internals.AbstractCommand.launchStream(AbstractCommand.java:166)
	at com.aragost.javahg.commands.LogCommand.execute(LogCommand.java:86)
	at com.aragost.javahg.Changeset.ensureAllDataLoaded(Changeset.java:333)
	at com.aragost.javahg.Changeset.getTimestamp(Changeset.java:271)
	at sonia.scm.repository.spi.HgTagsCommand$TagTransformer.apply(HgTagsCommand.java:102)
	at sonia.scm.repository.spi.HgTagsCommand$TagTransformer.apply(HgTagsCommand.java:87)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:616)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sonia.scm.repository.Tags.getTagByName(Tags.java:69)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at sonia.scm.api.v2.resources.DefaultChangesetToChangesetDtoMapper.getListOfObjects(DefaultChangesetToChangesetDtoMapper.java:154)
	at sonia.scm.api.v2.resources.DefaultChangesetToChangesetDtoMapper.createDto(DefaultChangesetToChangesetDtoMapper.java:131)
	at sonia.scm.api.v2.resources.DefaultChangesetToChangesetDtoMapperImpl.map(DefaultChangesetToChangesetDtoMapperImpl.java:28)
	at sonia.scm.activity.api.ActivityMapper.createDto(ActivityMapper.java:72)
	at sonia.scm.activity.api.ActivityMapperImpl.map(ActivityMapperImpl.java:23)
	at sonia.scm.activity.api.ActivityMapperImpl.activityListToActivityDtoList(ActivityMapperImpl.java:54)
	at sonia.scm.activity.api.ActivityMapperImpl.map(ActivityMapperImpl.java:40)
	at sonia.scm.activity.api.ActivityResource.getLatestActivity(ActivityResource.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.noRedirect(RepositoryLegacyProtocolRedirectFilter.java:127)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.checkPathElements(RepositoryLegacyProtocolRedirectFilter.java:100)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter$Worker.doFilter(RepositoryLegacyProtocolRedirectFilter.java:89)
	at sonia.scm.legacy.RepositoryLegacyProtocolRedirectFilter.doFilter(RepositoryLegacyProtocolRedirectFilter.java:71)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.filter.MDCFilter.doFilter(MDCFilter.java:105)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.web.security.TokenRefreshFilter.doFilter(TokenRefreshFilter.java:78)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.web.filter.AuthenticationFilter.processChain(AuthenticationFilter.java:264)
	at sonia.scm.web.filter.AuthenticationFilter.handleAuthentication(AuthenticationFilter.java:223)
	at sonia.scm.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:107)
	at sonia.scm.web.security.ApiAuthenticationFilter.doFilter(ApiAuthenticationFilter.java:99)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.security.TokenExpiredFilter.doFilter(TokenExpiredFilter.java:66)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at sonia.scm.filter.BaseUrlFilter.doFilter(BaseUrlFilter.java:109)
	at sonia.scm.web.filter.HttpFilter.doFilter(HttpFilter.java:93)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
`
#### Further information like screenshots
![image](https://user-images.githubusercontent.com/75020392/100225146-ab519000-2f15-11eb-9c61-7a263b37cbce.png)

**Comment by sdorra** [comment] 2020-11-28 10:07
This is the same root cause as #1446. We will close this issue to focus the conversation on #1446

**Closed by sdorra** 2020-11-28 10:07 UTC
