### ISSUE TITLE
apt issue

### ISSUE THREAD

**Issue by olaf7** [scm-manager/scm-manager#1269] opened 2020-07-29 14:50 UTC
OS: Debian Buster (stable, Debian 10)
Installed SCM-Manager 2.2.0 as per SCM-manager APT repo

Goal: upgrade from 2.2.0 to 2.3.0

Failed. Had to add the [arch=all] tag. Done. But now when running: **apt-get clean && apt-get update &&  apt-get upgrade** :

`W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/packages.scm-manager.org_repository_apt-v2-releases_dists_stable_InRelease`

**Comment by sdorra** [comment] 2020-07-30 05:21
Hi, the `[arch=all]` has made it into our [documentation](https://www.scm-manager.org/docs/2.3.x/en/installation/debian/). The `W: Invalid 'Date' entry in Release file` is a warning, because our apt repository does not use the `utc` timezone for the date in the release file. We will try to fix that. But this is a warning and should not block an installation or upgrade.

**Comment by olaf7** [comment] 2020-07-30 11:42
It does block an update:

```
root@server:~# dpkg -l |grep scm
ii  scm-server                            2.2.0                                all          The easiest way to share and manage your Git, Mercurial and Subversion repositories
root@server:~# apt-get install scm-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
scm-server is already the newest version (2.2.0).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
root@server:~# 
```

Obviously the same happens when using an other method such as aptitude.

**Comment by sdorra** [comment] 2020-07-30 12:51
This is really strange. I tested installation and upgrade with the docker image of debian 10 and it spit out the warning, but the upgrade was made. Could you check your apt logs for an error?

**Comment by sdorra** [comment] 2020-07-30 12:53
And could you please post your version of `apt`?

**Comment by olaf7** [comment] 2020-07-30 13:20
```
# dpkg -l |grep apt
ii  apt                                   1.8.2.1                              amd64        commandline package manager
```

No errors in /var/log/apt/*
As the index is not properly build/updated the following also not helps:
```
# apt-get install --reinstall scm-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 2 not upgraded.
Need to get 50.2 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://packages.scm-manager.org/repository/apt-v2-releases stable/main all scm-server all 2.2.0 [50.2 MB]
Fetched 50.2 MB in 2s (22.0 MB/s)      
(Reading database ... 181246 files and directories currently installed.)
Preparing to unpack .../scm-server_2.2.0_all.deb ...
Unpacking scm-server (2.2.0) over (2.2.0) ...
Setting up scm-server (2.2.0) ...
```

Obviously I should be able to fix this with a manual download and installing it using `dpkg`, but normal `apt` installling should work.

**Comment by sdorra** [comment] 2020-07-31 06:46
Sorry, but i can't reproduce this. I've get the warning, but everything works as expected.

However i was able to change the timezone for our apt repository, but the release file is only regenerated with the next release. So with the next release of SCM-Manager the date should be in utc format and the issue should be fixed.

**Comment by olaf7** [comment] 2020-07-31 13:16
My issue is on a Hetzner VPS. I tried to mimic it on another VPS, but I only got a spare one with Digital Ocean. Installing 2.3.0 worked fine there. I guess I have to manually install 2.3.0. So I did. Left me with a problem I have seen before. Will file a new issue. Manual install seems fine at first glance. Thanks!

**Comment by olaf7** [comment] 2020-09-30 10:46
The error is back. I do have the **[arch=all]** tag implemented.

**Comment by sdorra** [comment] 2020-09-30 14:02
Do you get any error message, beside the date warning? I can't reproduce the issue. I get the warning about the wrong date format, but the index is updated.

We have opened an issue for the date format and hopefully the issue is fixed with the next nexus release: 

* https://issues.sonatype.org/browse/NEXUS-24846

**Comment by olaf7** [comment] 2020-09-30 14:17
No other errors. (see below). Thanks for filing the bug. As before it prevents/blocks upgrades.

apt-get clean && apt-get update && apt-get upgrade
```
..,
Fetched 1,594 B in 3s (513 B/s)
Reading package lists... Done
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/packages.scm-manager.org_repository_apt-v2-releases_dists_stable_InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
...
```

**Comment by sdorra** [comment] 2020-10-13 07:47
The 'Invalid Date' problem seams to be fixed now:

```
# apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 https://packages.scm-manager.org/repository/apt-v2-releases stable InRelease [1594 B]
Get:5 https://packages.scm-manager.org/repository/apt-v2-releases stable/main all Packages [1988 B]
Fetched 3582 B in 0s (7247 B/s)
Reading package lists... Done
```

**Closed by sdorra** 2020-10-13 07:47 UTC
Labels: bug
