### ISSUE TITLE
debian package update overwrites /etc/default/scm-server

### ISSUE THREAD

**Issue by pobv** [scm-manager/scm-manager#1580] opened 2021-03-10 18:55 UTC
## Issue description

When auto-upgrading with the debian package, then apparently the upgrade overwrites the changes made in /etc/default/scm-server. This also overwrites important changes such as different ports. IMHO suggested changes in the configuration files (in the documentation it says overwrite the values in /etc/default/scm-server) should not be overwritten on upgrade. An alternative conf file for customization that is included and not overwritten would be fine as well.

#### Describe how to reproduce the bug

Install scm-server on debian via repository, change /etc/default/scm-server,
e.g. another port. Update with apt. (happened on upgrade to 2.14.1)

#### Describe your SCM-Manager setup

Standard install, but an nginx for certificate handling in front (reverse proxy) of the multipurpose machine. Port 8080 is already taken, using another port works well, but the config file /etc/default/scm-server is overwritten on upgrade (apt-get update && apt-get upgrade). After the upgrade changing the config files again and restarting works.

#### Which operating system, browser and versions do you use?

debian 10 on server, any browser

#### Log of the bug

```
# cat /var/log/dpkg.log | grep scm-server  | grep 2.14.1
2021-03-10 19:36:28 upgrade scm-server:all 2.14.0 2.14.1
2021-03-10 19:36:29 status unpacked scm-server:all 2.14.1
2021-03-10 19:36:29 configure scm-server:all 2.14.1 <none>
2021-03-10 19:36:29 status unpacked scm-server:all 2.14.1
2021-03-10 19:36:29 status half-configured scm-server:all 2.14.1
2021-03-10 19:36:30 status installed scm-server:all 2.14.1
```

**Comment by sdorra** [comment] 2021-03-12 06:45
The issue is fixed with #1574 which will be release with the upcoming 2.15.0 release.
It may be that this release overwrites the config one last time, but the following releases will no longer overwrite changed configs.

**Closed by sdorra** 2021-03-12 06:45 UTC
Labels: bug
